version: '3.8'
services:
  app:
    image: sv_shiny_basic:0.0.6
    container_name: datenportal
    restart: always
    ports:
      - '30910:80'
    networks:
      - net
    volumes:
      - /home/director/projects/datenportal/volume/app:/app
networks:
  net:
    driver: bridge
